### ISSUE TITLE
Android TV with veraion 9. SSLV3_ALERT_CERTIFICATE_UNKNOWN Error

### ISSUE THREAD

**Issue by muqeeta96** [farshid616/androidTV-controller-Python#2]
I am using TCL Android TV with Android Version 9. When I try to pair it with Android TV. I already generate certificate before paring
It causes the below error

`Traceback (most recent call last):
  File "/Users/abdulmuqeet/Desktop/android tv/Android-TV-Remote-Controller-Python-main/android_tv_remote.py", line 64, in <module>
    sending_key_socket.connect()
  File "/Users/abdulmuqeet/Desktop/android tv/Android-TV-Remote-Controller-Python-main/sending_keys.py", line 33, in connect
    self.ssl_sock.connect((self.host, self.port))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1412, in connect
    self._real_connect(addr, False)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1403, in _real_connect
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1006)`

**Comment by mattiullah86** [comment]
Have you got any solution of this. I am actually trying it on OnePlus android tv
